//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.UserValidation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserValidation.UserValidationSoap")]
    public interface UserValidationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginUser", ReplyAction="*")]
        Application.UserValidation.loginUserResponse loginUser(Application.UserValidation.loginUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Application.UserValidation.loginUserResponse> loginUserAsync(Application.UserValidation.loginUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginUser", Namespace="http://tempuri.org/", Order=0)]
        public Application.UserValidation.loginUserRequestBody Body;
        
        public loginUserRequest() {
        }
        
        public loginUserRequest(Application.UserValidation.loginUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginUserRequestBody() {
        }
        
        public loginUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Application.UserValidation.loginUserResponseBody Body;
        
        public loginUserResponse() {
        }
        
        public loginUserResponse(Application.UserValidation.loginUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Application.UserValidation.LoginResult loginUserResult;
        
        public loginUserResponseBody() {
        }
        
        public loginUserResponseBody(Application.UserValidation.LoginResult loginUserResult) {
            this.loginUserResult = loginUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserValidationSoapChannel : Application.UserValidation.UserValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserValidationSoapClient : System.ServiceModel.ClientBase<Application.UserValidation.UserValidationSoap>, Application.UserValidation.UserValidationSoap {
        
        public UserValidationSoapClient() {
        }
        
        public UserValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Application.UserValidation.loginUserResponse Application.UserValidation.UserValidationSoap.loginUser(Application.UserValidation.loginUserRequest request) {
            return base.Channel.loginUser(request);
        }
        
        public Application.UserValidation.LoginResult loginUser(string username, string password) {
            Application.UserValidation.loginUserRequest inValue = new Application.UserValidation.loginUserRequest();
            inValue.Body = new Application.UserValidation.loginUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Application.UserValidation.loginUserResponse retVal = ((Application.UserValidation.UserValidationSoap)(this)).loginUser(inValue);
            return retVal.Body.loginUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Application.UserValidation.loginUserResponse> Application.UserValidation.UserValidationSoap.loginUserAsync(Application.UserValidation.loginUserRequest request) {
            return base.Channel.loginUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Application.UserValidation.loginUserResponse> loginUserAsync(string username, string password) {
            Application.UserValidation.loginUserRequest inValue = new Application.UserValidation.loginUserRequest();
            inValue.Body = new Application.UserValidation.loginUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Application.UserValidation.UserValidationSoap)(this)).loginUserAsync(inValue);
        }
    }
}
